/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package administrador.Pantallas.Paneles;

import static administrador.Controladores.ControladorPantallas.ControladorComandas.calcMonto;
import administrador.Controladores.ControladorPantallas.TableModels.prodTableModel;
import administrador.Entidades.EntidadesAbstractas.Contenedor;
import administrador.Entidades.Pedido;

/**
 *
 * @author Merlin
 */
public class CargaPedidos extends javax.swing.JPanel {

    prodTableModel model = new prodTableModel();
    Pedido pedido;
    public CargaPedidos() {
        initComponents();
        tblProductos.setModel(model);
        
    }

    public void setPedido(Pedido pedido){
        model.setSelecPedido(pedido);
        this.pedido = pedido;
        cmbBoxStock.removeAllItems();
        for (int i = 0; i < Contenedor.LISTPRODUCTO.size(); i++) {
            cmbBoxStock.addItem(Contenedor.LISTPRODUCTO.get(i).getNombre());
        }
    }
    
    public void setTextMozo(String text){
    lblMozo.setText(text);
    }
    
    public void setTextCubierto(String text){
    lblCubierto.setText(text);
    }
    
    public void setTextMesa(String text){
    lblMesa.setText(text);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblMesa = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblMozo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblCubierto = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblMonto = new javax.swing.JLabel();
        btnIngresaProd = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        cmbBoxStock = new javax.swing.JComboBox<>();
        txtCantProd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("Mesa");

        lblMesa.setText("0");

        jLabel3.setText("Mozo");

        lblMozo.setText("0");

        jLabel5.setText("Cubiertos");

        lblCubierto.setText("0");

        jLabel7.setText("Monto");

        lblMonto.setText("0");

        btnIngresaProd.setText("Ingresar Producto");
        btnIngresaProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresaProdActionPerformed(evt);
            }
        });

        jLabel9.setText("Estado");

        lblEstado.setText("Vacia");

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblProductos);

        cmbBoxStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBoxStockActionPerformed(evt);
            }
        });

        jLabel2.setText("Cant");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIngresaProd)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbBoxStock, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCantProd)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblMozo, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCubierto)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblMonto))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblEstado)))
                        .addGap(0, 19, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblMesa)
                    .addComponent(jLabel3)
                    .addComponent(lblMozo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblCubierto)
                    .addComponent(jLabel7)
                    .addComponent(lblMonto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbBoxStock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantProd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIngresaProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblEstado))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresaProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresaProdActionPerformed
    pedido.getListaConsum().addConsumision((String)cmbBoxStock.getSelectedItem(), txtCantProd.getText());
    lblMonto.setText(calcMonto(pedido).toString());
    model.fireTableDataChanged();
    }//GEN-LAST:event_btnIngresaProdActionPerformed

    private void cmbBoxStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBoxStockActionPerformed
        
    }//GEN-LAST:event_cmbBoxStockActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresaProd;
    private javax.swing.JComboBox<String> cmbBoxStock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCubierto;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblMesa;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblMozo;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtCantProd;
    // End of variables declaration//GEN-END:variables
}
